# Header
menu:
  home: /
  technology: /categories/技术
  doodle: /categories/生活
  archive: /archives
  cv: /resume
  about: /about

#widgets
widgets:
  # - search
  # - photo
  # - category
  # - weixin
  # - calendar
  # - links
  # - tagcloud
  # - tag
  # - archive
  # - weibo

# Author
author: ecronic


# Content
#excerpt_link: More +

# highlight.js
highlight_theme: tomorrow